openapi: 3.2.0
info:
  description: This API allows partner cloud marketplaces to create and manage both Reseller and Customer accounts, as well as place orders of select Adobe products for those Customers. Before placing an Order, both a Reseller and Customer account must exist. Each Customer must be tied to a Reseller, and each Reseller must be tied to a Distributor.
  version: 1.0.0
  title: Commerce Partner Transfers API
servers:
- url: https://partners-stage.adobe.io/
tags:
- name: Transfers
  description: Membership Controller V 2
paths:
  /v2/memberships/{membership-id}/offers:
    get:
      tags:
      - Transfers
      summary: Preview Offers for Transfer for a Membership ID
      description: Preview Offers for Transfer for a Membership ID
      operationId: previewOffersUsingGET
      parameters:
      - name: ignore-order-return
        in: query
        description: ignore-order-return
        required: false
        schema:
          type: boolean
          default: false
      - name: membership-id
        in: path
        description: membership-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Processed Preview Offers for Transfer for Membership ID Request Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TransferOffersPreviewResource'
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Preview Offers for Transfer for Membership ID
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
  /v2/memberships/{membership-id}/transfers:
    post:
      tags:
      - Transfers
      summary: Transfer Subscriptions
      description: Transfer Subscriptions
      operationId: createTransferUsingPOST
      parameters:
      - name: ignore-order-return
        in: query
        description: ignore-order-return
        required: false
        schema:
          type: boolean
          default: false
      - name: membership-id
        in: path
        description: membership-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TransferOffers'
        '201':
          description: Created
        '202':
          description: Transfer Subscriptions Request Accepted Successfully
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Not Found
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferOffers'
        description: transferOffers
        required: true
  /v2/memberships/{membership-id}/transfers/{transfer-id}:
    get:
      tags:
      - Transfers
      summary: Get Transfer details for a Membership ID and Transfer ID
      description: Get Transfer details for a Membership ID and Transfer ID
      operationId: getTransferUsingGET
      parameters:
      - name: membership-id
        in: path
        description: membership-id
        required: true
        schema:
          type: string
      - name: transfer-id
        in: path
        description: transfer-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Processed Get Transfer details for a Membership ID and Transfer ID Request Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TransferOffersResource'
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Get Transfer details for a Membership ID and Transfer ID
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
  /v3/memberships/{membership-id}/offers:
    get:
      tags:
      - Transfers
      summary: Preview Offers for Transfer for a Membership ID
      description: Preview Offers for Transfer for a Membership ID
      operationId: previewOffersUsingGET_1
      parameters:
      - name: ignore-order-return
        in: query
        description: ignore-order-return
        required: false
        schema:
          type: boolean
          default: false
      - name: membership-id
        in: path
        description: membership-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Processed Preview Offers for Transfer for Membership ID Request Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TransferOffersPreviewResource'
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Preview Offers for Transfer for Membership ID
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
  /v3/memberships/{membership-id}/transfers:
    post:
      tags:
      - Transfers
      summary: Transfer Subscriptions
      description: Transfer Subscriptions
      operationId: createTransferUsingPOST_1
      parameters:
      - name: ignore-order-return
        in: query
        description: ignore-order-return
        required: false
        schema:
          type: boolean
          default: false
      - name: membership-id
        in: path
        description: membership-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TransferOffers'
        '201':
          description: Created
        '202':
          description: Transfer Subscriptions Request Accepted Successfully
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Not Found
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferOffers'
        description: transferOffers
        required: true
  /v3/memberships/{membership-id}/transfers/{transfer-id}:
    get:
      tags:
      - Transfers
      summary: Get Transfer details for a Membership ID and Transfer ID
      description: Get Transfer details for a Membership ID and Transfer ID
      operationId: getTransferUsingGET_1
      parameters:
      - name: membership-id
        in: path
        description: membership-id
        required: true
        schema:
          type: string
      - name: transfer-id
        in: path
        description: transfer-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Processed Get Transfer details for a Membership ID and Transfer ID Request Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TransferOffersResource'
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Get Transfer details for a Membership ID and Transfer ID
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
components:
  schemas:
    TransferOffersPreviewResource:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TransferOffersPreviewOfferResource'
        links:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLink'
        totalCount:
          type: integer
          format: int32
      title: TransferOffersPreviewResource
    Pair_string_string:
      type: object
      properties:
        key:
          type: string
        left:
          type: string
        right:
          type: string
        value:
          type: string
      title: Pair«string,string»
    TransferOffersLineItemDto:
      type: object
      properties:
        lineItemNumber:
          type: integer
          format: int32
        offerId:
          type: string
        quantity:
          type: integer
          format: int32
        subscriptionId:
          type: string
      title: TransferOffersLineItemDto
    TransferOffersLineItemResource:
      type: object
      properties:
        lineItemNumber:
          type: integer
          format: int32
        links:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLink'
        offerId:
          type: string
        quantity:
          type: integer
          format: int32
        subscriptionId:
          type: string
      title: TransferOffersLineItemResource
    TransferOffersPreviewOfferResource:
      type: object
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLink'
        offerId:
          type: string
        quantity:
          type: integer
          format: int32
        renewalDate:
          type: string
          example: yyyy-MM-dd
      title: TransferOffersPreviewOfferResource
    TransferOffersResource:
      type: object
      properties:
        creationDate:
          type: string
          example: yyyy-MM-dd'T'HH:mm:ss'Z'
        customerId:
          type: string
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/TransferOffersLineItemResource'
        links:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLink'
        membershipId:
          type: string
        resellerId:
          type: string
        status:
          type: string
        transferId:
          type: string
      title: TransferOffersResource
    TransferOffers:
      type: object
      properties:
        creationDate:
          type: string
          format: date-time
        customerId:
          type: string
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/TransferOffersLineItemDto'
        membershipId:
          type: string
        reason:
          type: string
        resellerId:
          type: string
        status:
          type: string
        transferId:
          type: string
      title: TransferOffers
    ResourceLink:
      type: object
      properties:
        headers:
          type: array
          items:
            $ref: '#/components/schemas/Pair_string_string'
        method:
          type: string
        uri:
          type: string
      title: ResourceLink
  securitySchemes:
    authorization:
      type: apiKey
      name: authorization
      in: header
    x-api-key:
      type: apiKey
      name: x-api-key
      in: header
