openapi: 3.2.0
info:
  title: Adobe Workfront Info API
  version: v19.0
servers:
- url: https://{domain}.my.workfront.com/attask/api/v19.0
  description: Production environment
- url: https://{domain}.preview.workfront.com/attask/api/v19.0
  description: Preview environment
security:
- ApiKeyHeader: []
- SessionIDHeader: []
- AtTaskCookie: []
- WFAuthCookie: []
tags:
- name: Info
paths:
  /info:
    summary: Get customer sso and api version information
    get:
      summary: Get customer sso and api version information
      operationId: info
      responses:
        '200':
          description: Great Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      sso:
                        type: object
                        properties:
                          ssoType:
                            type: string
                          providerURL:
                            type: string
                          providerPort:
                            type: number
                            format: int32
                          signoutURL:
                            type: string
                      versions:
                        type: array
                        items:
                          type: string
      tags:
      - Info
components:
  securitySchemes:
    SessionIDHeader:
      type: apiKey
      name: sessionID
      in: header
    AtTaskCookie:
      type: apiKey
      name: attask
      in: cookie
    WFAuthCookie:
      type: apiKey
      name: wf-auth
      in: cookie
    ApiKeyHeader:
      type: apiKey
      name: apiKey
      in: header
