openapi: 3.2.0
info:
  title: Catalog Service Batched requests API
  description: "Catalog is the system of record for data location and lineage within Adobe Experience Platform. Catalog Service does not contain the actual files or directories that contain the data. Instead, it holds the metadata and description of those files and directories.\n\nCatalog acts as a metadata store or \"catalog\" where you can find information about your data within Experience Platform.\n\nUse Catalog to answer the following questions: Where is my data located? At what stage of processing is this data? What systems or processes have acted on my data? What errors occurred during processing? If successful, how much data was processed?\n\n- **Related documentation**:\n    - [Catalog Service documentation](http://www.adobe.com/go/data-catalog-service-overview-en)\n\n- **Visualize API calls with Postman (a free, third-party software)**:\n    - [Catalog Service API Postman collection on GitHub](https://github.com/adobe/experience-platform-postman-samples/blob/master/apis/experience-platform/Catalog%20Service%20API.postman_collection.json)\n    - [Video guide for creating the Postman environment](https://video.tv.adobe.com/v/28832)\n    - [Steps for importing environments and collections in Postman](https://learning.postman.com/docs/getting-started/importing-and-exporting-data/)\n\n- **API paths**:\n    - PLATFORM Gateway URL: https://<span>platform.adobe.io/\n    - Base path for this API: /data/foundation/catalog\n    - Example of a complete path: https://<span>platform.adobe.io/data/foundation/catalog/batches\n\n- **Required headers**:\n    - All calls require the headers `Authorization`, `x-gw-ims-org-id`, and `x-api-key`. For more information on how to obtain these values, see the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).\n    - All resources in Experience Platform are isolated to specific virtual sandboxes. All requests to Platform APIs require the header `x-sandbox-name` whose value is the all-lowercase name of the sandbox the operation will take place in (for example, \"prod\"). See the [sandboxes overview](https://adobe.com/go/sandbox-overview-en) for more information.\n    - All requests with a payload in the request body (such as POST, PUT, and PATCH calls) must include the header `Content-Type` with a value of `application/json`.\n\n- **API error handling**:\n    - Refer to the Experience Platform API troubleshooting guide for [FAQs](https://experienceleague.adobe.com/docs/experience-platform/landing/troubleshooting.html#faq), [API status codes](https://experienceleague.adobe.com/docs/experience-platform/landing/troubleshooting.html#api-status-codes), and [request header errors](https://experienceleague.adobe.com/docs/experience-platform/landing/troubleshooting.html#request-header-errors).\n- **Sorting and filtering responses**:\n    - When performing listing (GET) requests in the Catalog Service API, you can use query parameters to [sort and filter responses](https://experienceleague.adobe.com/docs/experience-platform/catalog/api/filter-data.html)."
  version: '1.0'
servers:
- url: //{environment}.adobe.io/data/foundation/catalog
  variables:
    environment:
      default: platform
      enum:
      - platform
      - platform-stage
tags:
- name: Batched requests
  description: Batched requests allow users to supply an array of objects in the request payload, representing what would normally be individual requests.
paths:
  /:
    get:
      tags:
      - Batched requests
      summary: Retrieve a list of batched requests
      description: This request allows you to retrieve a list of batched requests which can be ordered as required. For example, the list can be ordered by created date in ascending order.
      operationId: listBatchedRequest
      parameters:
      - name: orderBy
        in: query
        description: Sort parameter and direction for sorting the response. Ex. orderBy=asc:created,updated. This was previously called sort.
        schema:
          type: string
      - $ref: '#/components/parameters/limit'
      - name: start
        in: query
        description: Specifies the offset of the pages of results. To get the first page of results, set the value to `start=0`.
        schema:
          type: integer
          default: 0
      - name: property
        in: query
        description: Regex used to filter objects in the response.
        schema:
          type: string
      - name: properties
        in: query
        description: A comma separated allowlist of top-level object properties to be returned in the response. Used to cut down the number of properties and amount of data returned in the response bodies.
        schema:
          type: string
      responses:
        200:
          description: serviceResources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serviceResources'
        404:
          description: Not found
          content: {}
        500:
          description: An internal server error has ocurred.
          content: {}
        default:
          description: An unexpected error has ocurred.
          content: {}
      deprecated: true
    post:
      tags:
      - Batched requests
      summary: Create a new batched request
      description: '**Note:** This endpoint has been deprecated. This request creates a new batched request which allows you to supply an array of objects in the request payload, representing what would normally be individual requests.'
      operationId: createBatchedRequest
      parameters:
      - $ref: '#/components/parameters/content-type'
      requestBody:
        description: The relative path of the resource.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/resourceItem'
        required: true
      responses:
        201:
          description: Array[ @/resource/resourceId ]
          headers:
            Location:
              description: The URI of the newly created resource
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        400:
          description: A bad request.
          content: {}
        403:
          description: Access is forbidden.
          content: {}
        500:
          description: An internal server error has ocurred.
          content: {}
        default:
          description: An unexpected error has ocurred.
          content: {}
      x-codegen-request-body-name: resources
      deprecated: true
components:
  schemas:
    resourceItem:
      type: object
      properties:
        id:
          type: string
          description: null
        method:
          type: string
          description: null
        headers:
          type: object
          properties: {}
          description: 'Example: "headers": {"if-match": "1.0.6"}'
          example:
            if-match: 1.0.6
        resource:
          type: string
          description: null
        body:
          type: object
          properties: {}
          description: null
    serviceResources:
      type: object
      properties:
        dataSource:
          type: string
          description: null
          example: foo_dataSource
        dataSet:
          type: string
          description: The ID of the dataset.
          example: foo_dataSet
        transform:
          type: string
          description: The transform ID.
  parameters:
    limit:
      name: limit
      in: query
      description: Limit response to a specified positive number of objects. The maximum number of objects that can be returned is 100.
      schema:
        type: integer
      example: 20
    content-type:
      name: content-type
      in: header
      description: Specifies the media type of the request body. Required for requests with a payload, such as POST, PUT, and PATCH. When sending a JSON payload, this must be set to `application/json`.
      required: true
      schema:
        type: string
        enum:
        - application/json
