openapi: 3.2.0
info:
  title: Data Hygiene Quota API
  description: Use the Data Hygiene REST API to schedule expiration dates for datasets or delete stored customer personal data in Experience Platform.
  version: 1.0.0
servers:
- url: https://{environment}.adobe.io
  variables:
    environment:
      default: platform
      enum:
      - platform
      - platform-stage
tags:
- name: Quota
  description: Use the `/quota` endpoint in the Data Hygiene API to monitor your Advanced Data Lifecycle Management usage against your organization’s quota limits for each job type.
paths:
  /quota:
    get:
      summary: List quota usage and limits
      description: 'Returns the current quota usage and limits for data hygiene operations for your organization.

        Quota amounts may differ based on organization entitlements such as Privacy and Security Shield or Health Care Shield.

        The consumed quota resets on the 1st of each month at 00:00 GMT and 00:00 GMT for daily quota.

        Filter by quota type using the `quotaType` query parameter.

        Quota type values include:

        - `datasetExpirationQuota`: This object shows the number of concurrently active dataset expirations for your organization, and your total allowance of expirations.

        - `dailyConsumerDeleteIdentitiesQuota`: This object shows the total number of record delete requests made by your organization today and your total daily allowance.

        Note: Only accepted requests are counted. If a workorder is rejected because it fails validation, those identity deletions do not count against your quota.

        - `monthlyConsumerDeleteIdentitiesQuota`: This object shows the total number of record delete requests made by your organization this month and your total monthly allowance.

        Note: Only accepted requests are counted. If a workorder is rejected because it fails validation, those identity deletions do not count against your quota.'
      operationId: listQuotas
      tags:
      - Quota
      parameters:
      - $ref: '#/components/parameters/ContentType'
      - $ref: '#/components/parameters/XApiKey'
      - $ref: '#/components/parameters/XImsOrgId'
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/quotaType'
      responses:
        '200':
          description: Successfully retrieved quota information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuotaResponse'
              examples:
                default:
                  summary: Example /quota GET response
                  value:
                    quotas:
                    - name: datasetExpirationQuota
                      description: The number of concurrently active dataset-expiration delete operations in all work order requests for the organization.
                      consumed: 11
                      quota: 75
                    - name: dailyConsumerDeleteIdentitiesQuota
                      description: The consumed number of deleted identities in all work order requests for the organization for today.
                      consumed: 314
                      quota: 700000
                    - name: monthlyConsumerDeleteIdentitiesQuota
                      description: The consumed number of deleted identities in all work order requests for the organization this month.
                      consumed: 2764
                      quota: 12000000
        '400':
          x-summary: Bad request
          description: The request could not be understood or was missing required parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '401':
          x-summary: Unauthorized
          description: Authentication failed or you do not have permissions for the requested operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse401'
        '500':
          x-summary: Internal server error
          description: This can occur if there is an issue on the server while processing the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
components:
  schemas:
    ErrorResponse500:
      type: object
      properties:
        error_code:
          type: string
          example: '500001'
        message:
          type: string
          example: Internal server error.
    QuotaResponse:
      type: object
      properties:
        quotas:
          type: array
          items:
            $ref: '#/components/schemas/Quota'
    ErrorResponse401:
      type: object
      properties:
        error_code:
          type: string
          example: '401013'
        message:
          type: string
          example: Unauthorized. Authentication failed or user does not have permissions for the requested operation.
    Quota:
      type: object
      properties:
        name:
          type: string
          description: The quota type identifier.
          example: datasetExpirationQuota
        description:
          type: string
          description: Description of what this quota limits.
          example: The number of concurrently active Expiration Dataset Delete operations in all work order requests for the organization.
        consumed:
          type: integer
          description: The amount of quota currently consumed. The consumed amount resets on the 1st of the month at 00:00 GMT and 00:00 GMT for daily quota.
          example: 314
        quota:
          type: integer
          description: The maximum allotment of this quota type for your organization.
          example: 700000
    ErrorResponse400:
      type: object
      properties:
        error_code:
          type: string
          example: '400001'
        message:
          type: string
          example: Bad request. The request could not be understood or was missing required parameters.
  parameters:
    Authorization:
      name: Authorization
      in: header
      required: true
      description: The bearer token for authentication. For more information, see the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
      schema:
        type: string
      example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.GOTCHARACTER.TOKENVALUE
    XApiKey:
      name: x-api-key
      in: header
      required: true
      description: The API key associated with your Experience Platform account. For more information, see the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
      schema:
        type: string
      example: 3c14558cb79f4ee6dd9884243314f482
    quotaType:
      in: query
      name: quotaType
      description: "Filter the response by quota type. If no quotaType parameter is provided, all quota values are returned in the API response. \n"
      required: false
      schema:
        type: string
        enum:
        - datasetExpirationQuota
        - dailyConsumerDeleteIdentitiesQuota
        - monthlyConsumerDeleteIdentitiesQuota
    XImsOrgId:
      name: x-gw-ims-org-id
      in: header
      required: true
      description: The organization ID associated with your Experience Platform account. See the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
      schema:
        type: string
    ContentType:
      name: Content-Type
      in: header
      required: true
      description: The media type of the request body. Should be 'application/json'.
      schema:
        type: string
      example: application/json
