openapi: 3.2.0
info:
  title: Adobe Workfront Login API
  version: v19.0
servers:
- url: https://{domain}.my.workfront.com/attask/api/v19.0
  description: Production environment
- url: https://{domain}.preview.workfront.com/attask/api/v19.0
  description: Preview environment
security:
- ApiKeyHeader: []
- SessionIDHeader: []
- AtTaskCookie: []
- WFAuthCookie: []
tags:
- name: Login
paths:
  /login:
    summary: Login
    post:
      summary: Login
      operationId: login
      parameters:
      - name: username
        in: query
        description: Username
        required: true
        schema:
          type: string
      - name: password
        in: query
        description: Password
        required: true
        schema:
          type: string
      - name: subdomain
        in: query
        description: Subdomain
        required: true
        schema:
          type: string
      - name: timeToLive
        in: query
        description: Session time to live in seconds
        required: false
        schema:
          type: number
          format: int32
      responses:
        '200':
          description: Successfully authenticated. The session ID is returned in a cookie named `attask`. You need to include this cookie in subsequent requests.
          headers:
            Set-Cookie:
              schema:
                type: string
                description: Authentication cookie named `attask`
                example: attask=59982a73ed2a4574b4eaba70baf2e11e; Path=/; HttpOnly; Max-Age=28800; Expires=Fri, 27-Sep-2024 19:36:24 GMT
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      sessionID:
                        type: string
                      userID:
                        type: string
                      userCompanyID:
                        type: string
                      isAdmin:
                        type: boolean
                      timeZone:
                        type: string
                      timeZoneName:
                        type: string
                      locale:
                        type: string
                      iso3Country:
                        type: string
                      iso3Language:
                        type: string
                      customerID:
                        type: string
                      tenantID:
                        type: string
                      hasInsightsAccess:
                        type: boolean
                      currency:
                        type: object
                        properties:
                          ID:
                            type: string
                          symbol:
                            type: string
                          groupingSeparator:
                            type: string
                          decimalSeparator:
                            type: string
                          fractionDigits:
                            type: number
                            format: int32
                          useNegativeSign:
                            type: boolean
                      versionInformation:
                        type: object
                        properties:
                          version:
                            type: string
                          release:
                            type: string
                          buildNumber:
                            type: string
                          lastUpdated:
                            type: string
                            format: date-time
                          currentAPI:
                            type: number
                            format: int32
                          apiVersions:
                            type: object
                            additionalProperties:
                              type: string
      security: []
      tags:
      - Login
components:
  securitySchemes:
    SessionIDHeader:
      type: apiKey
      name: sessionID
      in: header
    AtTaskCookie:
      type: apiKey
      name: attask
      in: cookie
    WFAuthCookie:
      type: apiKey
      name: wf-auth
      in: cookie
    ApiKeyHeader:
      type: apiKey
      name: apiKey
      in: header
