openapi: 3.2.0
info:
  version: 2.4.6
  title: Commerce Customer REST endpoints - All inclusive Customers/me/activate API
  description:
    $ref: intro/redocly-intro.md
servers:
- url: https://example.com/rest/default
tags:
- name: customers/me/activate
paths:
  /V1/customers/me/activate:
    put:
      tags:
      - customers/me/activate
      description: Activate a customer account using a key that was sent in a confirmation email.
      operationId: PutV1CustomersMeActivate
      responses:
        '200':
          description: 200 Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customer-data-customer-interface'
            application/xml:
              schema:
                $ref: '#/components/schemas/customer-data-customer-interface'
        '401':
          description: 401 Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
      summary: customers/me/activate
      requestBody:
        content:
          application/json:
            schema:
              required:
              - confirmationKey
              properties:
                confirmationKey:
                  type: string
              type: object
              xml:
                name: request
          application/xml:
            schema:
              required:
              - confirmationKey
              properties:
                confirmationKey:
                  type: string
              type: object
              xml:
                name: request
components:
  schemas:
    error-errors:
      type: array
      description: Errors list
      items:
        $ref: '#/components/schemas/error-errors-item'
    customer-data-customer-extension-interface:
      type: object
      description: ExtensionInterface class for @see \Magento\Customer\Api\Data\CustomerInterface
      properties:
        company_attributes:
          $ref: '#/components/schemas/company-data-company-customer-interface'
        assistance_allowed:
          type: integer
        is_subscribed:
          type: boolean
    error-errors-item:
      type: object
      description: Error details
      properties:
        message:
          type: string
          description: Error message
        parameters:
          $ref: '#/components/schemas/error-parameters'
    customer-data-region-extension-interface:
      type: object
      description: ExtensionInterface class for @see \Magento\Customer\Api\Data\RegionInterface
    framework-attribute-interface:
      type: object
      description: Interface for custom attribute value.
      properties:
        attribute_code:
          type: string
          description: Attribute code
        value:
          type: string
          description: Attribute value
      required:
      - attribute_code
      - value
    customer-data-customer-interface:
      type: object
      description: Customer entity interface for API handling.
      properties:
        id:
          type: integer
          description: Customer id
        group_id:
          type: integer
          description: Group id
        default_billing:
          type: string
          description: Default billing address id
        default_shipping:
          type: string
          description: Default shipping address id
        confirmation:
          type: string
          description: Confirmation
        created_at:
          type: string
          description: Created at time
        updated_at:
          type: string
          description: Updated at time
        created_in:
          type: string
          description: Created in area
        dob:
          type: string
          description: In keeping with current security and privacy best practices, be sure you are aware of any potential legal and security risks associated with the storage of customers’ full date of birth (month, day, year) along with other personal identifiers (e.g., full name) before collecting or processing such data.
        email:
          type: string
          description: Email address
        firstname:
          type: string
          description: First name
        lastname:
          type: string
          description: Last name
        middlename:
          type: string
          description: Middle name
        prefix:
          type: string
          description: Prefix
        suffix:
          type: string
          description: Suffix
        gender:
          type: integer
          description: Gender
        store_id:
          type: integer
          description: Store id
        taxvat:
          type: string
          description: Tax Vat
        website_id:
          type: integer
          description: Website id
        addresses:
          type: array
          description: Customer addresses.
          items:
            $ref: '#/components/schemas/customer-data-address-interface'
        disable_auto_group_change:
          type: integer
          description: Disable auto group change flag.
        extension_attributes:
          $ref: '#/components/schemas/customer-data-customer-extension-interface'
        custom_attributes:
          type: array
          description: Custom attributes values.
          items:
            $ref: '#/components/schemas/framework-attribute-interface'
      required:
      - email
      - firstname
      - lastname
    company-data-company-customer-extension-interface:
      type: object
      description: ExtensionInterface class for @see \Magento\Company\Api\Data\CompanyCustomerInterface
    customer-data-address-extension-interface:
      type: object
      description: ExtensionInterface class for @see \Magento\Customer\Api\Data\AddressInterface
    error-parameters-item:
      type: object
      description: Error parameters item
      properties:
        resources:
          type: string
          description: ACL resource
        fieldName:
          type: string
          description: Missing or invalid field name
        fieldValue:
          type: string
          description: Incorrect field value
    error-response:
      type: object
      properties:
        message:
          type: string
          description: Error message
        errors:
          $ref: '#/components/schemas/error-errors'
        code:
          type: integer
          description: Error code
        parameters:
          $ref: '#/components/schemas/error-parameters'
        trace:
          type: string
          description: Stack trace
      required:
      - message
    company-data-company-customer-interface:
      type: object
      description: Extended customer custom attributes interface.
      properties:
        customer_id:
          type: integer
          description: Customer ID.
        company_id:
          type: integer
          description: Company ID.
        job_title:
          type: string
          description: Get job title.
        status:
          type: integer
          description: Customer status.
        telephone:
          type: string
          description: Get telephone.
        extension_attributes:
          $ref: '#/components/schemas/company-data-company-customer-extension-interface'
    error-parameters:
      type: array
      description: Error parameters list
      items:
        $ref: '#/components/schemas/error-parameters-item'
    customer-data-address-interface:
      type: object
      description: Customer address interface.
      properties:
        id:
          type: integer
          description: ID
        customer_id:
          type: integer
          description: Customer ID
        region:
          $ref: '#/components/schemas/customer-data-region-interface'
        region_id:
          type: integer
          description: Region ID
        country_id:
          type: string
          description: Country code in ISO_3166-2 format
        street:
          type: array
          description: Street
          items:
            type: string
        company:
          type: string
          description: Company
        telephone:
          type: string
          description: Telephone number
        fax:
          type: string
          description: Fax number
        postcode:
          type: string
          description: Postcode
        city:
          type: string
          description: City name
        firstname:
          type: string
          description: First name
        lastname:
          type: string
          description: Last name
        middlename:
          type: string
          description: Middle name
        prefix:
          type: string
          description: Prefix
        suffix:
          type: string
          description: Suffix
        vat_id:
          type: string
          description: Vat id
        default_shipping:
          type: boolean
          description: If this address is default shipping address.
        default_billing:
          type: boolean
          description: If this address is default billing address
        extension_attributes:
          $ref: '#/components/schemas/customer-data-address-extension-interface'
        custom_attributes:
          type: array
          description: Custom attributes values.
          items:
            $ref: '#/components/schemas/framework-attribute-interface'
    customer-data-region-interface:
      type: object
      description: Customer address region interface.
      properties:
        region_code:
          type: string
          description: Region code
        region:
          type: string
          description: Region
        region_id:
          type: integer
          description: Region id
        extension_attributes:
          $ref: '#/components/schemas/customer-data-region-extension-interface'
      required:
      - region_code
      - region
      - region_id
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
x-tagGroups:
- name: applepay
  tags:
  - applepay/auth
- name: carts
  tags:
  - carts/guest-carts/{cartId}/checkGiftCard/{giftCardCode}
  - carts/guest-carts/{cartId}/giftCards
  - carts/guest-carts/{cartId}/giftCards/{giftCardCode}
  - carts/mine
  - carts/mine/balance/apply
  - carts/mine/checkGiftCard/{giftCardCode}
  - carts/mine/collect-totals
  - carts/mine/payment-information
  - carts/mine/po-payment-information
  - carts/mine/set-payment-information
- name: customers
  tags:
  - customers
  - customers/isEmailAvailable
  - customers/me/activate
  - customers/me/password
  - customers/password
  - customers/resetPassword
  - customers/{customerId}/password/resetLinkToken/{resetPasswordLinkToken}
- name: directory
  tags:
  - directory/countries
  - directory/countries/{countryId}
  - directory/currency
- name: giftregistry
  tags:
  - giftregistry/mine/estimate-shipping-methods
- name: guest carts
  tags:
  - guest-carts
  - guest-carts/{cartId}
  - guest-carts/{cartId}/billing-address
  - guest-carts/{cartId}/collect-totals
  - guest-carts/{cartId}/coupons
  - guest-carts/{cartId}/coupons/{couponCode}
  - guest-carts/{cartId}/estimate-shipping-methods
  - guest-carts/{cartId}/gift-message
  - guest-carts/{cartId}/gift-message/{itemId}
  - guest-carts/{cartId}/items
  - guest-carts/{cartId}/items/{itemId}
  - guest-carts/{cartId}/order
  - guest-carts/{cartId}/payment-information
  - guest-carts/{cartId}/payment-methods
  - guest-carts/{cartId}/selected-payment-method
  - guest-carts/{cartId}/set-payment-information
  - guest-carts/{cartId}/shipping-information
  - guest-carts/{cartId}/shipping-methods
  - guest-carts/{cartId}/totals
  - guest-carts/{cartId}/totals-information
- name: guest giftregistry
  tags:
  - guest-giftregistry/{cartId}/estimate-shipping-methods
- name: integration
  tags:
  - integration/admin/token
  - integration/customer/revoke-customer-token
  - integration/customer/token
- name: inventory
  tags:
  - inventory/in-store-pickup/pickup-locations/
- name: negotiable carts
  tags:
  - negotiable-carts/{cartId}/billing-address
  - negotiable-carts/{cartId}/coupons
  - negotiable-carts/{cartId}/coupons/{couponCode}
  - negotiable-carts/{cartId}/estimate-shipping-methods
  - negotiable-carts/{cartId}/estimate-shipping-methods-by-address-id
  - negotiable-carts/{cartId}/giftCards
  - negotiable-carts/{cartId}/giftCards/{giftCardCode}
  - negotiable-carts/{cartId}/payment-information
  - negotiable-carts/{cartId}/set-payment-information
  - negotiable-carts/{cartId}/shipping-information
  - negotiable-carts/{cartId}/totals
- name: products render info
  tags:
  - products-render-info
- name: purchase order carts
  tags:
  - purchase-order-carts/{cartId}/payment-information
  - purchase-order-carts/{cartId}/set-payment-information
- name: quick checkout
  tags:
  - quick-checkout/account-details
  - quick-checkout/has-account
  - quick-checkout/storefront/has-account
- name: requisition_lists
  tags:
  - requisition_lists
- name: reward
  tags:
  - reward/mine/use-reward
- name: search
  tags:
  - search
- name: tfa
  tags:
  - tfa/provider/authy/activate
  - tfa/provider/authy/authenticate
  - tfa/provider/authy/authenticate-onetouch
  - tfa/provider/authy/configure
  - tfa/provider/authy/send-token/{via}
  - tfa/provider/duo_security/activate
  - tfa/provider/duo_security/authenticate
  - tfa/provider/duo_security/configure
  - tfa/provider/duo_security/get-authentication-data
  - tfa/provider/google/activate
  - tfa/provider/google/authenticate
  - tfa/provider/google/configure
  - tfa/provider/u2fkey/activate
  - tfa/provider/u2fkey/authentication-challenge
  - tfa/provider/u2fkey/configure
  - tfa/provider/u2fkey/verify
  - tfa/tfat-providers-to-activate
  - tfa/tfat-user-providers
