openapi: 3.2.0
info:
  title: Catalog Service Batched requests API
  description: Catalog is the system of record for data location and lineage within Adobe Experience Platform.
  version: '1.0'
servers:
- url: //{environment}.adobe.io/data/foundation/catalog
  variables:
    environment:
      default: platform
      enum:
      - platform
      - platform-stage
tags:
- name: Batched requests
  description: Batched requests allow users to supply an array of objects in the request payload, representing what would normally be individual requests.
paths:
  /:
    get:
      tags:
      - Batched requests
      summary: Retrieve a list of batched requests
      description: This request allows you to retrieve a list of batched requests which can be ordered as required. For example, the list can be ordered by created date in ascending order.
      operationId: listBatchedRequest
      parameters:
      - name: orderBy
        in: query
        description: Sort parameter and direction for sorting the response. Ex. orderBy=asc:created,updated. This was previously called sort.
        schema:
          type: string
      - $ref: '#/components/parameters/limit'
      - name: start
        in: query
        description: Specifies the offset of the pages of results. To get the first page of results, set the value to `start=0`.
        schema:
          type: integer
          default: 0
      - name: property
        in: query
        description: Regex used to filter objects in the response.
        schema:
          type: string
      - name: properties
        in: query
        description: A comma separated allowlist of top-level object properties to be returned in the response. Used to cut down the number of properties and amount of data returned in the response bodies.
        schema:
          type: string
      responses:
        200:
          description: serviceResources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serviceResources'
        404:
          description: Not found
          content: {}
        500:
          description: An internal server error has ocurred.
          content: {}
        default:
          description: An unexpected error has ocurred.
          content: {}
      deprecated: true
    post:
      tags:
      - Batched requests
      summary: Create a new batched request
      description: '**Note:** This endpoint has been deprecated. This request creates a new batched request which allows you to supply an array of objects in the request payload, representing what would normally be individual requests.'
      operationId: createBatchedRequest
      parameters:
      - $ref: '#/components/parameters/content-type'
      requestBody:
        description: The relative path of the resource.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/resourceItem'
        required: true
      responses:
        201:
          description: Array[ @/resource/resourceId ]
          headers:
            Location:
              description: The URI of the newly created resource
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        400:
          description: A bad request.
          content: {}
        403:
          description: Access is forbidden.
          content: {}
        500:
          description: An internal server error has ocurred.
          content: {}
        default:
          description: An unexpected error has ocurred.
          content: {}
      x-codegen-request-body-name: resources
      deprecated: true
components:
  schemas:
    resourceItem:
      type: object
      properties:
        id:
          type: string
          description: null
        method:
          type: string
          description: null
        headers:
          type: object
          properties: {}
          description: 'Example: "headers": {"if-match": "1.0.6"}'
          example:
            if-match: 1.0.6
        resource:
          type: string
          description: null
        body:
          type: object
          properties: {}
          description: null
    serviceResources:
      type: object
      properties:
        dataSource:
          type: string
          description: null
          example: foo_dataSource
        dataSet:
          type: string
          description: The ID of the dataset.
          example: foo_dataSet
        transform:
          type: string
          description: The transform ID.
  parameters:
    limit:
      name: limit
      in: query
      description: Limit response to a specified positive number of objects. The maximum number of objects that can be returned is 100.
      schema:
        type: integer
      example: 20
    content-type:
      name: content-type
      in: header
      description: Specifies the media type of the request body. Required for requests with a payload, such as POST, PUT, and PATCH. When sending a JSON payload, this must be set to `application/json`.
      required: true
      schema:
        type: string
        enum:
        - application/json
