openapi: 3.2.0
info:
  description: This API allows partner cloud marketplaces to create and manage both Reseller and Customer accounts, as well as place orders of select Adobe products for those Customers. Before placing an Order, both a Reseller and Customer account must exist. Each Customer must be tied to a Reseller, and each Reseller must be tied to a Distributor.
  version: 1.0.0
  title: Commerce Partner Subscriptions API
servers:
- url: https://partners-stage.adobe.io/
tags:
- name: Subscriptions
  description: Customer Subscription Controller V 2
paths:
  /v2/customers/{customer-id}/subscriptions:
    get:
      tags:
      - Subscriptions
      summary: Get All Subscriptions for a Customer
      description: Get All Subscriptions for a Customer with a corresponding Customer ID.
      operationId: findSubscriptionsUsingGET
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Processed Get All Subscriptions for a Customer Request Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SubscriptionHistoryResource'
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Get All Subscriptions for a Customer
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
  /v2/customers/{customer-id}/subscriptions/{subscription-id}:
    get:
      tags:
      - Subscriptions
      summary: Get Subscription Details
      description: Get Subscription Details with corresponding Customer ID and Subsciption ID. Can receive the current quantity, autorenewal status, creation date, and more.
      operationId: findSubscriptionUsingGET
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      - name: subscription-id
        in: path
        description: subscription-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Processed Get Subscription Details Request Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SubscriptionResource'
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Find Customer Subscription
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
    patch:
      tags:
      - Subscriptions
      summary: Update Subscription Auto-Renewal
      description: Update the auto renewal status and quantity of licenses to renew. Subscriptions that are created by an order will be set to auto-renew by default.
      operationId: updateSubscriptionAutoRenewalUsingPATCH
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      - name: subscription-id
        in: path
        description: subscription-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Processed Update Subscription Auto-Renewal Request Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SubscriptionResource'
        '204':
          description: No Content
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Update Subscription Auto-Renewal
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
        description: subscription
        required: true
  /v3/customers/{customer-id}/subscriptions:
    get:
      tags:
      - Subscriptions
      summary: Get All Subscriptions for a Customer
      description: Get All Subscriptions for a Customer with a corresponding Customer ID.
      operationId: findSubscriptionsUsingGET_1
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Processed Get All Subscriptions for a Customer Request Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SubscriptionHistoryResource'
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Get All Subscriptions for a Customer
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
  /v3/customers/{customer-id}/subscriptions/{subscription-id}:
    get:
      tags:
      - Subscriptions
      summary: Get Subscription Details
      description: Get Subscription Details with corresponding Customer ID and Subsciption ID. Can receive the current quantity, autorenewal status, creation date, and more.
      operationId: findSubscriptionUsingGET_1
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      - name: subscription-id
        in: path
        description: subscription-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Processed Get Subscription Details Request Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SubscriptionResource'
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Find Customer Subscription
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
    patch:
      tags:
      - Subscriptions
      summary: Update Subscription Auto-Renewal
      description: Update the auto renewal status and quantity of licenses to renew. Subscriptions that are created by an order will be set to auto-renew by default.
      operationId: updateSubscriptionAutoRenewalUsingPATCH_1
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      - name: subscription-id
        in: path
        description: subscription-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Processed Update Subscription Auto-Renewal Request Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SubscriptionResource'
        '204':
          description: No Content
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Update Subscription Auto-Renewal
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
        description: subscription
        required: true
components:
  schemas:
    Subscription:
      type: object
      properties:
        autoRenewal:
          $ref: '#/components/schemas/AutoRenewal'
        creationDate:
          type: string
          format: date-time
        currentQuantity:
          type: integer
          format: int32
        offerId:
          type: string
        renewalDate:
          type: string
          format: date-time
        status:
          type: string
        subscriptionId:
          type: string
        usedQuantity:
          type: integer
          format: int32
      title: Subscription
    AutoRenewal:
      type: object
      properties:
        enabled:
          type: boolean
        renewalQuantity:
          type: integer
          format: int32
      title: AutoRenewal
    Pair_string_string:
      type: object
      properties:
        key:
          type: string
        left:
          type: string
        right:
          type: string
        value:
          type: string
      title: Pair«string,string»
    SubscriptionHistoryResource:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SubscriptionResource'
        links:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLink'
        totalCount:
          type: integer
          format: int32
      title: SubscriptionHistoryResource
    SubscriptionResource:
      type: object
      properties:
        autoRenewal:
          $ref: '#/components/schemas/AutoRenewal'
        creationDate:
          type: string
          example: yyyy-MM-dd'T'HH:mm:ss'Z'
        currentQuantity:
          type: integer
          format: int32
        links:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLink'
        offerId:
          type: string
        renewalDate:
          type: string
          example: yyyy-MM-dd
        status:
          type: string
        subscriptionId:
          type: string
        usedQuantity:
          type: integer
          format: int32
      title: SubscriptionResource
    ResourceLink:
      type: object
      properties:
        headers:
          type: array
          items:
            $ref: '#/components/schemas/Pair_string_string'
        method:
          type: string
        uri:
          type: string
      title: ResourceLink
  securitySchemes:
    authorization:
      type: apiKey
      name: authorization
      in: header
    x-api-key:
      type: apiKey
      name: x-api-key
      in: header
