openapi: 3.2.0
info:
  title: Segmentation Service Estimates API
  description: Adobe Experience Platform Segmentation Service provides a user interface and RESTful API that allows you to create audiences through segment definitions or other sources from your Real-Time Customer Profile data.
  version: '1.0'
servers:
- url: //{environment}.adobe.io/data/core/ups
  variables:
    environment:
      default: platform
      enum:
      - platform
      - platform-stage
tags:
- name: Estimates
  description: Estimates provide statistical information on a segment definition, such as the projected audience size and confidence interval. More information about using this set of endpoints can be found in the previews and estimates endpoint guide.
paths:
  /estimate/{ESTIMATE_ID}:
    get:
      tags:
      - Estimates
      summary: Retrieve the results of an estimate job
      operationId: retrieveEstimate
      parameters:
      - $ref: '#/components/parameters/authorization'
      - $ref: '#/components/parameters/x-api-key'
      - $ref: '#/components/parameters/x-gw-ims-org-id'
      - $ref: '#/components/parameters/x-sandbox-name'
      - name: ESTIMATE_ID
        in: path
        description: The ID of the estimate job.
        required: true
        schema:
          type: string
      responses:
        200:
          x-summary: Success
          description: The estimate job was successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EstimateResponse'
        403:
          x-summary: Missing access permissions
          description: Access is forbidden.
          content: {}
        404:
          x-summary: Not found
          description: The estimate job was not found.
          content: {}
        503:
          x-summary: Service unavailable
          description: The service is unavailable.
          content: {}
components:
  parameters:
    x-api-key:
      name: x-api-key
      in: header
      description: The API key which can be copied from your Experience Platform integration. For more information on how to obtain this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
      required: true
      schema:
        type: string
    authorization:
      name: Authorization
      in: header
      description: The access token which can be copied from your Experience Platform integration, prefixed with "Bearer ". For more information on how to obtain this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
      required: true
      schema:
        type: string
    x-sandbox-name:
      name: x-sandbox-name
      in: header
      description: All resources in Experience Platform are isolated to specific virtual sandboxes. Requests to Platform APIs require a header that specifies the name of the sandbox in which the operation will take place. See the [sandboxes overview](https://adobe.com/go/sandbox-overview-en) for more information.
      required: true
      schema:
        type: string
    x-gw-ims-org-id:
      name: x-gw-ims-org-id
      in: header
      description: The Organization ID which can be copied from your Experience Platform integration. For more information on how to obtain this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
      required: true
      schema:
        type: string
  schemas:
    PreviewLink:
      required:
      - preview
      type: object
      properties:
        preview:
          type: string
          description: The URI to get more information about the estimate.
          example: https://platform.adobe.io/data/core/ups/preview/app-32be0328-3f31-4b64-8d84-acd0c4fbdad3/execution/0?previewQueryId={QUERY_ID}
    EstimateResponse:
      type: object
      properties:
        estimatedSize:
          type: integer
          format: int32
          example: 35935
        numRowsToRead:
          type: integer
          format: int32
          example: 35935
        estimatedNamespaceDistribution:
          type: array
          items:
            type: object
            properties:
              namespaceId:
                type: string
                example: '4'
              profilesMatchedSoFar:
                type: integer
                example: 11986
        state:
          type: string
          example: RESULT_READY
        profilesReadSoFar:
          type: integer
          format: int32
          example: 35935
        standardError:
          type: integer
          format: int32
          example: 0
        error:
          type: object
          properties:
            description:
              type: string
              example: ''
            traceback:
              type: string
              example: ''
        profilesMatchedSoFar:
          type: integer
          example: 12123
        totalRows:
          type: integer
          format: int32
          example: 35935
        confidenceInterval:
          type: string
          example: 95%
        _links:
          $ref: '#/components/schemas/PreviewLink'
