openapi: 3.2.0
info:
  description: This API allows partner cloud marketplaces to create and manage both Reseller and Customer accounts, as well as place orders of select Adobe products for those Customers. Before placing an Order, both a Reseller and Customer account must exist. Each Customer must be tied to a Reseller, and each Reseller must be tied to a Distributor.
  version: 1.0.0
  title: Commerce Partner Orders API
servers:
- url: https://partners-stage.adobe.io/
tags:
- name: Orders
  description: Customer Order Controller V 3
paths:
  /v2/customers/{customer-id}/orderpreviews:
    post:
      tags:
      - Orders
      summary: Preview an order
      description: Preview an order
      operationId: createOrderPreviewUsingPOST
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Preview Order Request Accepted Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderResource'
        '201':
          description: Created
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Not Found
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        description: order
        required: true
  /v2/customers/{customer-id}/orders:
    get:
      tags:
      - Orders
      summary: Get Order History
      description: Get Order History
      operationId: findOrdersUsingGET
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Get Order History Request Processed Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderHistoryResource'
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Find Customer Orders
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
    post:
      tags:
      - Orders
      summary: Creates an order
      description: Creates an order
      operationId: createOrderUsingPOST
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Order'
        '201':
          description: Created
        '202':
          description: Create Order Request Accepted Successfully
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Not Found
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        description: order
        required: true
  /v2/customers/{customer-id}/orders/{order-id}:
    get:
      tags:
      - Orders
      summary: Get Order Details
      description: Get Order Details
      operationId: findOrderUsingGET
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      - name: order-id
        in: path
        description: order-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Get Order Details Request Processed Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderResource'
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Find Customer Order
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
    patch:
      tags:
      - Orders
      summary: Cancel Order
      description: Cancel an Order for a Customer
      operationId: cancelOrderUsingPATCH
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      - name: order-id
        in: path
        description: order-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderResource'
        '202':
          description: Cancel Order Request Accepted Successfully
        '204':
          description: No Content
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Cancel Order
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        description: order
        required: true
  /v3/customers/{customer-id}/orders:
    get:
      tags:
      - Orders
      summary: Get Order History
      description: Get Order History
      operationId: findOrdersUsingGET_1
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      - name: end-date
        in: query
        description: end-date
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: limit
        required: false
        schema:
          type: integer
          format: int32
      - name: offer-id
        in: query
        description: offer-id
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: offset
        in: query
        description: offset
        required: false
        schema:
          type: integer
          format: int32
      - name: order-type
        in: query
        description: order-type
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: reference-order-id
        in: query
        description: reference-order-id
        required: false
        schema:
          type: string
      - name: start-date
        in: query
        description: start-date
        required: false
        schema:
          type: string
      - name: status
        in: query
        description: status
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: subscription-id
        in: query
        description: subscription-id
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: Get Order History Request Processed Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderHistoryResource'
        '400':
          description: 'Bad '
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Find Customer Orders
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
    post:
      tags:
      - Orders
      summary: Creates an order
      description: Creates an order
      operationId: createOrderUsingPOST_1
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Order'
        '201':
          description: Created
        '202':
          description: Create Order Request Accepted Successfully
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Not Found
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        description: order
        required: true
  /v3/customers/{customer-id}/orders/{order-id}:
    get:
      tags:
      - Orders
      summary: Get Order Details
      description: Get Order Details
      operationId: findOrderUsingGET_1
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      - name: order-id
        in: path
        description: order-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Get Order Details Request Processed Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderResource'
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Find Customer Order
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
    patch:
      tags:
      - Orders
      summary: Update externalReferenceId of order
      description: Update externalReferenceId of Order
      operationId: updateOrderUsingPATCH
      parameters:
      - name: customer-id
        in: path
        description: customer-id
        required: true
        schema:
          type: string
      - name: order-id
        in: path
        description: order-id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ExternalId Updated Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderResource'
        '204':
          description: No Content
        '400':
          description: Request could not be processed because of bad request
        '401':
          description: Unauthorized
        '403':
          description: Api Key is invalid
        '404':
          description: Unable to Find Customer Order
        '500':
          description: Error with external dependency or network
      security:
      - authorization: []
      - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        description: order
        required: true
components:
  schemas:
    Subscription:
      type: object
      properties:
        autoRenewal:
          $ref: '#/components/schemas/AutoRenewal'
        creationDate:
          type: string
          format: date-time
        currentQuantity:
          type: integer
          format: int32
        offerId:
          type: string
        renewalDate:
          type: string
          format: date-time
        status:
          type: string
        subscriptionId:
          type: string
        usedQuantity:
          type: integer
          format: int32
      title: Subscription
    OrderResource:
      type: object
      properties:
        creationDate:
          type: string
          example: yyyy-MM-dd'T'HH:mm:ss'Z'
        currencyCode:
          type: string
        customerId:
          type: string
        externalReferenceId:
          type: string
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderLineItemResource'
        links:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLink'
        orderId:
          type: string
        orderType:
          type: string
          enum:
          - NEW
          - PREVIEW
          - PREVIEW_RENEWAL
          - RENEWAL
          - RETURN
          - TRANSFER
        referenceOrderId:
          type: string
        status:
          type: string
      title: OrderResource
    AutoRenewal:
      type: object
      properties:
        enabled:
          type: boolean
        renewalQuantity:
          type: integer
          format: int32
      title: AutoRenewal
    Pair_string_string:
      type: object
      properties:
        key:
          type: string
        left:
          type: string
        right:
          type: string
        value:
          type: string
      title: Pair«string,string»
    OrderLineItemResource:
      type: object
      properties:
        extLineItemNumber:
          type: integer
          format: int32
        links:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLink'
        offerId:
          type: string
        quantity:
          type: integer
          format: int32
        status:
          type: string
        subscriptionId:
          type: string
      title: OrderLineItemResource
    Reference:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
      title: Reference
    OrderHistoryResource:
      type: object
      properties:
        count:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderResource'
        limit:
          type: integer
          format: int32
        links:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLink'
        offset:
          type: integer
          format: int32
        totalCount:
          type: integer
          format: int32
      title: OrderHistoryResource
    Order:
      type: object
      required:
      - currencyCode
      properties:
        creationDate:
          type: string
          format: date-time
        currencyCode:
          type: string
          pattern: ^[A-Z]{3}$
        customerId:
          type: string
        externalReferenceId:
          type: string
          minLength: 0
          maxLength: 35
          pattern: ^[^<>[\"]]*$
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderLineItemDto'
        orderId:
          type: string
        orderSource:
          type: string
          enum:
          - MARKETPLACE
          - NO_DISCOUNT
          - SUBSCRIPTION_SERVICE
        orderType:
          type: string
          enum:
          - NEW
          - PREVIEW
          - PREVIEW_RENEWAL
          - RENEWAL
          - RETURN
          - TRANSFER
        reason:
          type: string
        referenceOrderId:
          type: string
        references:
          type: array
          items:
            $ref: '#/components/schemas/Reference'
        status:
          type: string
      title: Order
    OrderLineItemDto:
      type: object
      properties:
        extLineItemNumber:
          type: integer
          format: int32
          minimum: 1
          maximum: 999999
        offerId:
          type: string
        quantity:
          type: integer
          format: int32
          minimum: 1
          maximum: 999999
        status:
          type: string
        subscription:
          $ref: '#/components/schemas/Subscription'
        subscriptionId:
          type: string
      title: OrderLineItemDto
    ResourceLink:
      type: object
      properties:
        headers:
          type: array
          items:
            $ref: '#/components/schemas/Pair_string_string'
        method:
          type: string
        uri:
          type: string
      title: ResourceLink
  securitySchemes:
    authorization:
      type: apiKey
      name: authorization
      in: header
    x-api-key:
      type: apiKey
      name: x-api-key
      in: header
