openapi: 3.2.0
info:
  title: Adobe Workfront Userdelegation API
  version: v19.0
servers:
- url: https://{domain}.my.workfront.com/attask/api/v19.0
  description: Production environment
- url: https://{domain}.preview.workfront.com/attask/api/v19.0
  description: Preview environment
security:
- ApiKeyHeader: []
- SessionIDHeader: []
- AtTaskCookie: []
- WFAuthCookie: []
tags:
- name: Userdelegation
paths:
  /userdelegation/{id}:
    get:
      summary: Get for UserDelegation
      operationId: getUserDelegation
      parameters:
      - name: id
        in: path
        description: Object ID
        required: true
        schema:
          type: string
      - name: fields
        in: query
        description: JSON array defining the fields to retrieve
        required: false
        example: '["ID", "name"]'
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: Great Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./UserDelegation.json
        '422':
          $ref: '#/components/responses/422_UNPROCESSABLE_ENTITY'
        '400':
          $ref: '#/components/responses/400_BAD_REQUEST'
        '429':
          $ref: '#/components/responses/429_TOO_MANY_REQUESTS'
        '403':
          $ref: '#/components/responses/403_FORBIDDEN'
        '401':
          $ref: '#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: '#/components/responses/404_NOT_FOUND'
        '500':
          $ref: '#/components/responses/500_INTERNAL_SERVER_ERROR'
        '410':
          $ref: '#/components/responses/410_GONE'
      tags:
      - Userdelegation
    put:
      summary: Edit a UserDelegation
      operationId: editUserDelegation
      parameters:
      - name: id
        in: path
        description: Object ID
        required: true
        schema:
          type: string
      - name: fields
        in: query
        description: JSON array defining the fields to retrieve
        required: false
        example: '["ID", "name"]'
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: Great Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./UserDelegation.json
        '422':
          $ref: '#/components/responses/422_UNPROCESSABLE_ENTITY'
        '400':
          $ref: '#/components/responses/400_BAD_REQUEST'
        '429':
          $ref: '#/components/responses/429_TOO_MANY_REQUESTS'
        '403':
          $ref: '#/components/responses/403_FORBIDDEN'
        '401':
          $ref: '#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: '#/components/responses/404_NOT_FOUND'
        '500':
          $ref: '#/components/responses/500_INTERNAL_SERVER_ERROR'
        '410':
          $ref: '#/components/responses/410_GONE'
      tags:
      - Userdelegation
    delete:
      summary: Delete for UserDelegation
      operationId: deleteUserDelegation
      parameters:
      - name: id
        in: path
        description: Object ID
        required: true
        schema:
          type: string
      - name: force
        in: query
        description: force delete flag
        required: false
        schema:
          type: boolean
      responses:
        '200':
          $ref: '#/components/responses/200_OK'
        '422':
          $ref: '#/components/responses/422_UNPROCESSABLE_ENTITY'
        '400':
          $ref: '#/components/responses/400_BAD_REQUEST'
        '429':
          $ref: '#/components/responses/429_TOO_MANY_REQUESTS'
        '403':
          $ref: '#/components/responses/403_FORBIDDEN'
        '401':
          $ref: '#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: '#/components/responses/404_NOT_FOUND'
        '500':
          $ref: '#/components/responses/500_INTERNAL_SERVER_ERROR'
        '410':
          $ref: '#/components/responses/410_GONE'
      tags:
      - Userdelegation
  /userdelegation:
    get:
      summary: Bulk Get for UserDelegation
      operationId: getUserDelegations
      parameters:
      - name: id
        in: query
        description: Object IDs
        required: true
        schema:
          type: string
          example: id1,id2,id3
      - name: fields
        in: query
        description: JSON array defining the fields to retrieve
        required: false
        example: '["ID", "name"]'
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: Great Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    anyOf:
                    - $ref: ./UserDelegation.json
                    - type: array
                      items:
                        $ref: ./UserDelegation.json
        '422':
          $ref: '#/components/responses/422_UNPROCESSABLE_ENTITY'
        '400':
          $ref: '#/components/responses/400_BAD_REQUEST'
        '429':
          $ref: '#/components/responses/429_TOO_MANY_REQUESTS'
        '403':
          $ref: '#/components/responses/403_FORBIDDEN'
        '401':
          $ref: '#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: '#/components/responses/404_NOT_FOUND'
        '500':
          $ref: '#/components/responses/500_INTERNAL_SERVER_ERROR'
        '410':
          $ref: '#/components/responses/410_GONE'
      tags:
      - Userdelegation
    put:
      summary: Bulk Edit for UserDelegation
      operationId: editUserDelegations
      parameters:
      - name: fields
        in: query
        description: JSON array defining the fields to retrieve
        required: false
        example: '["ID", "name"]'
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
              - $ref: ./UserDelegation.json
              - type: array
                items:
                  $ref: ./UserDelegation.json
      responses:
        '200':
          description: Great Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    anyOf:
                    - $ref: ./UserDelegation.json
                    - type: array
                      items:
                        $ref: ./UserDelegation.json
        '422':
          $ref: '#/components/responses/422_UNPROCESSABLE_ENTITY'
        '400':
          $ref: '#/components/responses/400_BAD_REQUEST'
        '429':
          $ref: '#/components/responses/429_TOO_MANY_REQUESTS'
        '403':
          $ref: '#/components/responses/403_FORBIDDEN'
        '401':
          $ref: '#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: '#/components/responses/404_NOT_FOUND'
        '500':
          $ref: '#/components/responses/500_INTERNAL_SERVER_ERROR'
        '410':
          $ref: '#/components/responses/410_GONE'
      tags:
      - Userdelegation
    post:
      summary: Create a userdelegation
      operationId: addUserDelegations
      parameters:
      - name: fields
        in: query
        description: JSON array defining the fields to retrieve
        required: false
        example: '["ID", "name"]'
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
              - $ref: ./UserDelegation.json
              - type: array
                items:
                  $ref: ./UserDelegation.json
      responses:
        '200':
          description: Great Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    anyOf:
                    - $ref: ./UserDelegation.json
                    - type: array
                      items:
                        $ref: ./UserDelegation.json
        '422':
          $ref: '#/components/responses/422_UNPROCESSABLE_ENTITY'
        '400':
          $ref: '#/components/responses/400_BAD_REQUEST'
        '429':
          $ref: '#/components/responses/429_TOO_MANY_REQUESTS'
        '403':
          $ref: '#/components/responses/403_FORBIDDEN'
        '401':
          $ref: '#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: '#/components/responses/404_NOT_FOUND'
        '500':
          $ref: '#/components/responses/500_INTERNAL_SERVER_ERROR'
        '410':
          $ref: '#/components/responses/410_GONE'
      tags:
      - Userdelegation
    delete:
      summary: Bulk Delete for UserDelegation
      operationId: deleteUserDelegations
      parameters:
      - name: id
        in: query
        description: Object IDs
        required: true
        schema:
          type: string
          example: id1,id2,id3
      - name: force
        in: query
        description: force delete flag
        required: false
        schema:
          type: boolean
      responses:
        '200':
          $ref: '#/components/responses/200_OK'
        '422':
          $ref: '#/components/responses/422_UNPROCESSABLE_ENTITY'
        '400':
          $ref: '#/components/responses/400_BAD_REQUEST'
        '429':
          $ref: '#/components/responses/429_TOO_MANY_REQUESTS'
        '403':
          $ref: '#/components/responses/403_FORBIDDEN'
        '401':
          $ref: '#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: '#/components/responses/404_NOT_FOUND'
        '500':
          $ref: '#/components/responses/500_INTERNAL_SERVER_ERROR'
        '410':
          $ref: '#/components/responses/410_GONE'
      tags:
      - Userdelegation
  /userdelegation/count:
    get:
      summary: Count of userdelegation
      operationId: countUserDelegations
      parameters:
      - name: filters
        in: query
        description: JSON representing the filtering conditions
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Great Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      count:
                        type: integer
                        format: int32
        '422':
          $ref: '#/components/responses/422_UNPROCESSABLE_ENTITY'
        '400':
          $ref: '#/components/responses/400_BAD_REQUEST'
        '429':
          $ref: '#/components/responses/429_TOO_MANY_REQUESTS'
        '403':
          $ref: '#/components/responses/403_FORBIDDEN'
        '401':
          $ref: '#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: '#/components/responses/404_NOT_FOUND'
        '500':
          $ref: '#/components/responses/500_INTERNAL_SERVER_ERROR'
        '410':
          $ref: '#/components/responses/410_GONE'
      tags:
      - Userdelegation
  /userdelegation/search:
    get:
      summary: Search of userdelegation
      operationId: searchUserDelegations
      parameters:
      - name: filters
        in: query
        description: JSON representing the filtering conditions
        required: false
        content:
          application/json:
            schema:
              type: object
      - name: fields
        in: query
        description: JSON array defining the fields to retrieve
        required: false
        example: '["ID", "name"]'
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      - name: listOptions
        in: query
        description: JSON object defining the list options
        required: false
        content:
          application/json:
            schema:
              $ref: ./ListOptions.json
      responses:
        '200':
          description: Great Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: ./UserDelegation.json
        '422':
          $ref: '#/components/responses/422_UNPROCESSABLE_ENTITY'
        '400':
          $ref: '#/components/responses/400_BAD_REQUEST'
        '429':
          $ref: '#/components/responses/429_TOO_MANY_REQUESTS'
        '403':
          $ref: '#/components/responses/403_FORBIDDEN'
        '401':
          $ref: '#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: '#/components/responses/404_NOT_FOUND'
        '500':
          $ref: '#/components/responses/500_INTERNAL_SERVER_ERROR'
        '410':
          $ref: '#/components/responses/410_GONE'
      tags:
      - Userdelegation
  /userdelegation/report:
    get:
      summary: Report of userdelegation
      operationId: reportUserDelegations
      parameters:
      - name: filters
        in: query
        description: JSON representing the filtering conditions
        required: false
        content:
          application/json:
            schema:
              type: object
      - name: listOptions
        in: query
        description: JSON object defining the list options
        required: false
        content:
          application/json:
            schema:
              $ref: ./ListOptions.json
      responses:
        '200':
          description: Great Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
        '422':
          $ref: '#/components/responses/422_UNPROCESSABLE_ENTITY'
        '400':
          $ref: '#/components/responses/400_BAD_REQUEST'
        '429':
          $ref: '#/components/responses/429_TOO_MANY_REQUESTS'
        '403':
          $ref: '#/components/responses/403_FORBIDDEN'
        '401':
          $ref: '#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: '#/components/responses/404_NOT_FOUND'
        '500':
          $ref: '#/components/responses/500_INTERNAL_SERVER_ERROR'
        '410':
          $ref: '#/components/responses/410_GONE'
      tags:
      - Userdelegation
components:
  responses:
    200_OK:
      description: Great Success
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  success:
                    type: boolean
    429_TOO_MANY_REQUESTS:
      description: Too many concurrent API requests for the given customer.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  class:
                    type: string
                  message:
                    type: string
    500_INTERNAL_SERVER_ERROR:
      description: An unexpected error occurred.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  class:
                    type: string
                  message:
                    type: string
    422_UNPROCESSABLE_ENTITY:
      description: The request contains invalid data.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  class:
                    type: string
                  message:
                    type: string
    401_UNAUTHORIZED:
      description: The request is not authenticated.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  class:
                    type: string
                  message:
                    type: string
    400_BAD_REQUEST:
      description: The operation is not supported.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  class:
                    type: string
                  message:
                    type: string
    404_NOT_FOUND:
      description: The requested resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  class:
                    type: string
                  message:
                    type: string
    403_FORBIDDEN:
      description: The user does not have permission to perform the operation.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  class:
                    type: string
                  message:
                    type: string
    410_GONE:
      description: The requested resource is no longer available in this API version.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  class:
                    type: string
                  message:
                    type: string
  securitySchemes:
    SessionIDHeader:
      type: apiKey
      name: sessionID
      in: header
    AtTaskCookie:
      type: apiKey
      name: attask
      in: cookie
    WFAuthCookie:
      type: apiKey
      name: wf-auth
      in: cookie
    ApiKeyHeader:
      type: apiKey
      name: apiKey
      in: header
