openapi: 3.2.0
info:
  version: 2.4.6
  title: Commerce Customer REST endpoints - All inclusive Requisition Lists API
  description:
    $ref: intro/redocly-intro.md
servers:
- url: https://example.com/rest/default
tags:
- name: requisition_lists
paths:
  /V1/requisition_lists:
    post:
      tags:
      - requisition_lists
      description: Save Requisition List
      operationId: PostV1Requisition_lists
      responses:
        '200':
          description: 200 Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/requisition-list-data-requisition-list-interface'
            application/xml:
              schema:
                $ref: '#/components/schemas/requisition-list-data-requisition-list-interface'
        '401':
          description: 401 Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
      summary: requisition_lists
      requestBody:
        content:
          application/json:
            schema:
              required:
              - requisitionList
              properties:
                requisitionList:
                  $ref: '#/components/schemas/requisition-list-data-requisition-list-interface'
              type: object
              xml:
                name: request
          application/xml:
            schema:
              required:
              - requisitionList
              properties:
                requisitionList:
                  $ref: '#/components/schemas/requisition-list-data-requisition-list-interface'
              type: object
              xml:
                name: request
components:
  schemas:
    error-errors:
      type: array
      description: Errors list
      items:
        $ref: '#/components/schemas/error-errors-item'
    requisition-list-data-requisition-list-item-extension-interface:
      type: object
      description: ExtensionInterface class for @see \Magento\RequisitionList\Api\Data\RequisitionListItemInterface
    error-errors-item:
      type: object
      description: Error details
      properties:
        message:
          type: string
          description: Error message
        parameters:
          $ref: '#/components/schemas/error-parameters'
    requisition-list-data-requisition-list-item-interface:
      type: object
      description: Interface RequisitionListItemInterface
      properties:
        id:
          type: integer
          description: Requisition List ID.
        sku:
          type: string
          description: Product SKU.
        requisition_list_id:
          type: integer
          description: Requisition List ID.
        qty:
          type: number
          description: Product Qty.
        options:
          type: array
          description: Requisition list item options.
          items:
            type: string
        store_id:
          type: integer
          description: Store ID.
        added_at:
          type: string
          description: Added_at value.
        extension_attributes:
          $ref: '#/components/schemas/requisition-list-data-requisition-list-item-extension-interface'
      required:
      - id
      - sku
      - requisition_list_id
      - qty
      - options
      - store_id
      - added_at
    error-parameters-item:
      type: object
      description: Error parameters item
      properties:
        resources:
          type: string
          description: ACL resource
        fieldName:
          type: string
          description: Missing or invalid field name
        fieldValue:
          type: string
          description: Incorrect field value
    error-response:
      type: object
      properties:
        message:
          type: string
          description: Error message
        errors:
          $ref: '#/components/schemas/error-errors'
        code:
          type: integer
          description: Error code
        parameters:
          $ref: '#/components/schemas/error-parameters'
        trace:
          type: string
          description: Stack trace
      required:
      - message
    requisition-list-data-requisition-list-interface:
      type: object
      description: Interface RequisitionListInterface
      properties:
        id:
          type: integer
          description: Requisition List ID
        customer_id:
          type: integer
          description: Customer ID
        name:
          type: string
          description: Requisition List Name
        updated_at:
          type: string
          description: Requisition List Update Time
        description:
          type: string
          description: Requisition List Description
        items:
          type: array
          description: Requisition List Items
          items:
            $ref: '#/components/schemas/requisition-list-data-requisition-list-item-interface'
        extension_attributes:
          $ref: '#/components/schemas/requisition-list-data-requisition-list-extension-interface'
      required:
      - id
      - customer_id
      - name
      - updated_at
      - description
      - items
    error-parameters:
      type: array
      description: Error parameters list
      items:
        $ref: '#/components/schemas/error-parameters-item'
    requisition-list-data-requisition-list-extension-interface:
      type: object
      description: ExtensionInterface class for @see \Magento\RequisitionList\Api\Data\RequisitionListInterface
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
x-tagGroups:
- name: applepay
  tags:
  - applepay/auth
- name: carts
  tags:
  - carts/guest-carts/{cartId}/checkGiftCard/{giftCardCode}
  - carts/guest-carts/{cartId}/giftCards
  - carts/guest-carts/{cartId}/giftCards/{giftCardCode}
  - carts/mine
  - carts/mine/balance/apply
  - carts/mine/checkGiftCard/{giftCardCode}
  - carts/mine/collect-totals
  - carts/mine/payment-information
  - carts/mine/po-payment-information
  - carts/mine/set-payment-information
- name: customers
  tags:
  - customers
  - customers/isEmailAvailable
  - customers/me/activate
  - customers/me/password
  - customers/password
  - customers/resetPassword
  - customers/{customerId}/password/resetLinkToken/{resetPasswordLinkToken}
- name: directory
  tags:
  - directory/countries
  - directory/countries/{countryId}
  - directory/currency
- name: giftregistry
  tags:
  - giftregistry/mine/estimate-shipping-methods
- name: guest carts
  tags:
  - guest-carts
  - guest-carts/{cartId}
  - guest-carts/{cartId}/billing-address
  - guest-carts/{cartId}/collect-totals
  - guest-carts/{cartId}/coupons
  - guest-carts/{cartId}/coupons/{couponCode}
  - guest-carts/{cartId}/estimate-shipping-methods
  - guest-carts/{cartId}/gift-message
  - guest-carts/{cartId}/gift-message/{itemId}
  - guest-carts/{cartId}/items
  - guest-carts/{cartId}/items/{itemId}
  - guest-carts/{cartId}/order
  - guest-carts/{cartId}/payment-information
  - guest-carts/{cartId}/payment-methods
  - guest-carts/{cartId}/selected-payment-method
  - guest-carts/{cartId}/set-payment-information
  - guest-carts/{cartId}/shipping-information
  - guest-carts/{cartId}/shipping-methods
  - guest-carts/{cartId}/totals
  - guest-carts/{cartId}/totals-information
- name: guest giftregistry
  tags:
  - guest-giftregistry/{cartId}/estimate-shipping-methods
- name: integration
  tags:
  - integration/admin/token
  - integration/customer/revoke-customer-token
  - integration/customer/token
- name: inventory
  tags:
  - inventory/in-store-pickup/pickup-locations/
- name: negotiable carts
  tags:
  - negotiable-carts/{cartId}/billing-address
  - negotiable-carts/{cartId}/coupons
  - negotiable-carts/{cartId}/coupons/{couponCode}
  - negotiable-carts/{cartId}/estimate-shipping-methods
  - negotiable-carts/{cartId}/estimate-shipping-methods-by-address-id
  - negotiable-carts/{cartId}/giftCards
  - negotiable-carts/{cartId}/giftCards/{giftCardCode}
  - negotiable-carts/{cartId}/payment-information
  - negotiable-carts/{cartId}/set-payment-information
  - negotiable-carts/{cartId}/shipping-information
  - negotiable-carts/{cartId}/totals
- name: products render info
  tags:
  - products-render-info
- name: purchase order carts
  tags:
  - purchase-order-carts/{cartId}/payment-information
  - purchase-order-carts/{cartId}/set-payment-information
- name: quick checkout
  tags:
  - quick-checkout/account-details
  - quick-checkout/has-account
  - quick-checkout/storefront/has-account
- name: requisition_lists
  tags:
  - requisition_lists
- name: reward
  tags:
  - reward/mine/use-reward
- name: search
  tags:
  - search
- name: tfa
  tags:
  - tfa/provider/authy/activate
  - tfa/provider/authy/authenticate
  - tfa/provider/authy/authenticate-onetouch
  - tfa/provider/authy/configure
  - tfa/provider/authy/send-token/{via}
  - tfa/provider/duo_security/activate
  - tfa/provider/duo_security/authenticate
  - tfa/provider/duo_security/configure
  - tfa/provider/duo_security/get-authentication-data
  - tfa/provider/google/activate
  - tfa/provider/google/authenticate
  - tfa/provider/google/configure
  - tfa/provider/u2fkey/activate
  - tfa/provider/u2fkey/authentication-challenge
  - tfa/provider/u2fkey/configure
  - tfa/provider/u2fkey/verify
  - tfa/tfat-providers-to-activate
  - tfa/tfat-user-providers
