openapi: 3.2.0
info:
  version: 2.4.6
  title: Commerce Customer REST endpoints - All inclusive Negotiable Carts/{cart Id}/estimate Shipping Methods By Address ID API
  description:
    $ref: intro/redocly-intro.md
servers:
- url: https://example.com/rest/default
tags:
- name: negotiable-carts/{cartId}/estimate-shipping-methods-by-address-id
paths:
  /V1/negotiable-carts/{cartId}/estimate-shipping-methods-by-address-id:
    post:
      tags:
      - negotiable-carts/{cartId}/estimate-shipping-methods-by-address-id
      description: Estimate shipping
      operationId: PostV1NegotiablecartsCartIdEstimateshippingmethodsbyaddressid
      parameters:
      - name: cartId
        in: path
        required: true
        description: The shopping cart ID.
        schema:
          type: integer
      responses:
        '200':
          description: 200 Success.
          content:
            application/json:
              schema:
                type: array
                description: An array of shipping methods.
                items:
                  $ref: '#/components/schemas/quote-data-shipping-method-interface'
            application/xml:
              schema:
                type: array
                description: An array of shipping methods.
                items:
                  $ref: '#/components/schemas/quote-data-shipping-method-interface'
        '401':
          description: 401 Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
      summary: negotiable-carts/{cartId}/estimate-shipping-methods-by-address-id
      requestBody:
        content:
          application/json:
            schema:
              required:
              - addressId
              properties:
                addressId:
                  type: integer
                  description: The estimate address id
              type: object
              xml:
                name: request
          application/xml:
            schema:
              required:
              - addressId
              properties:
                addressId:
                  type: integer
                  description: The estimate address id
              type: object
              xml:
                name: request
components:
  schemas:
    error-errors:
      type: array
      description: Errors list
      items:
        $ref: '#/components/schemas/error-errors-item'
    error-errors-item:
      type: object
      description: Error details
      properties:
        message:
          type: string
          description: Error message
        parameters:
          $ref: '#/components/schemas/error-parameters'
    quote-data-shipping-method-extension-interface:
      type: object
      description: ExtensionInterface class for @see \Magento\Quote\Api\Data\ShippingMethodInterface
    error-parameters-item:
      type: object
      description: Error parameters item
      properties:
        resources:
          type: string
          description: ACL resource
        fieldName:
          type: string
          description: Missing or invalid field name
        fieldValue:
          type: string
          description: Incorrect field value
    error-response:
      type: object
      properties:
        message:
          type: string
          description: Error message
        errors:
          $ref: '#/components/schemas/error-errors'
        code:
          type: integer
          description: Error code
        parameters:
          $ref: '#/components/schemas/error-parameters'
        trace:
          type: string
          description: Stack trace
      required:
      - message
    quote-data-shipping-method-interface:
      type: object
      description: Interface ShippingMethodInterface
      properties:
        carrier_code:
          type: string
          description: Shipping carrier code.
        method_code:
          type: string
          description: Shipping method code.
        carrier_title:
          type: string
          description: Shipping carrier title. Otherwise, null.
        method_title:
          type: string
          description: Shipping method title. Otherwise, null.
        amount:
          type: number
          description: Shipping amount in store currency.
        base_amount:
          type: number
          description: Shipping amount in base currency.
        available:
          type: boolean
          description: The value of the availability flag for the current shipping method.
        extension_attributes:
          $ref: '#/components/schemas/quote-data-shipping-method-extension-interface'
        error_message:
          type: string
          description: Shipping Error message.
        price_excl_tax:
          type: number
          description: Shipping price excl tax.
        price_incl_tax:
          type: number
          description: Shipping price incl tax.
      required:
      - carrier_code
      - method_code
      - amount
      - base_amount
      - available
      - error_message
      - price_excl_tax
      - price_incl_tax
    error-parameters:
      type: array
      description: Error parameters list
      items:
        $ref: '#/components/schemas/error-parameters-item'
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
x-tagGroups:
- name: applepay
  tags:
  - applepay/auth
- name: carts
  tags:
  - carts/guest-carts/{cartId}/checkGiftCard/{giftCardCode}
  - carts/guest-carts/{cartId}/giftCards
  - carts/guest-carts/{cartId}/giftCards/{giftCardCode}
  - carts/mine
  - carts/mine/balance/apply
  - carts/mine/checkGiftCard/{giftCardCode}
  - carts/mine/collect-totals
  - carts/mine/payment-information
  - carts/mine/po-payment-information
  - carts/mine/set-payment-information
- name: customers
  tags:
  - customers
  - customers/isEmailAvailable
  - customers/me/activate
  - customers/me/password
  - customers/password
  - customers/resetPassword
  - customers/{customerId}/password/resetLinkToken/{resetPasswordLinkToken}
- name: directory
  tags:
  - directory/countries
  - directory/countries/{countryId}
  - directory/currency
- name: giftregistry
  tags:
  - giftregistry/mine/estimate-shipping-methods
- name: guest carts
  tags:
  - guest-carts
  - guest-carts/{cartId}
  - guest-carts/{cartId}/billing-address
  - guest-carts/{cartId}/collect-totals
  - guest-carts/{cartId}/coupons
  - guest-carts/{cartId}/coupons/{couponCode}
  - guest-carts/{cartId}/estimate-shipping-methods
  - guest-carts/{cartId}/gift-message
  - guest-carts/{cartId}/gift-message/{itemId}
  - guest-carts/{cartId}/items
  - guest-carts/{cartId}/items/{itemId}
  - guest-carts/{cartId}/order
  - guest-carts/{cartId}/payment-information
  - guest-carts/{cartId}/payment-methods
  - guest-carts/{cartId}/selected-payment-method
  - guest-carts/{cartId}/set-payment-information
  - guest-carts/{cartId}/shipping-information
  - guest-carts/{cartId}/shipping-methods
  - guest-carts/{cartId}/totals
  - guest-carts/{cartId}/totals-information
- name: guest giftregistry
  tags:
  - guest-giftregistry/{cartId}/estimate-shipping-methods
- name: integration
  tags:
  - integration/admin/token
  - integration/customer/revoke-customer-token
  - integration/customer/token
- name: inventory
  tags:
  - inventory/in-store-pickup/pickup-locations/
- name: negotiable carts
  tags:
  - negotiable-carts/{cartId}/billing-address
  - negotiable-carts/{cartId}/coupons
  - negotiable-carts/{cartId}/coupons/{couponCode}
  - negotiable-carts/{cartId}/estimate-shipping-methods
  - negotiable-carts/{cartId}/estimate-shipping-methods-by-address-id
  - negotiable-carts/{cartId}/giftCards
  - negotiable-carts/{cartId}/giftCards/{giftCardCode}
  - negotiable-carts/{cartId}/payment-information
  - negotiable-carts/{cartId}/set-payment-information
  - negotiable-carts/{cartId}/shipping-information
  - negotiable-carts/{cartId}/totals
- name: products render info
  tags:
  - products-render-info
- name: purchase order carts
  tags:
  - purchase-order-carts/{cartId}/payment-information
  - purchase-order-carts/{cartId}/set-payment-information
- name: quick checkout
  tags:
  - quick-checkout/account-details
  - quick-checkout/has-account
  - quick-checkout/storefront/has-account
- name: requisition_lists
  tags:
  - requisition_lists
- name: reward
  tags:
  - reward/mine/use-reward
- name: search
  tags:
  - search
- name: tfa
  tags:
  - tfa/provider/authy/activate
  - tfa/provider/authy/authenticate
  - tfa/provider/authy/authenticate-onetouch
  - tfa/provider/authy/configure
  - tfa/provider/authy/send-token/{via}
  - tfa/provider/duo_security/activate
  - tfa/provider/duo_security/authenticate
  - tfa/provider/duo_security/configure
  - tfa/provider/duo_security/get-authentication-data
  - tfa/provider/google/activate
  - tfa/provider/google/authenticate
  - tfa/provider/google/configure
  - tfa/provider/u2fkey/activate
  - tfa/provider/u2fkey/authentication-challenge
  - tfa/provider/u2fkey/configure
  - tfa/provider/u2fkey/verify
  - tfa/tfat-providers-to-activate
  - tfa/tfat-user-providers
