openapi: 3.2.0
info:
  title: Data Distiller Authorization IP Validation API
  description: Use the Adobe Experience Platform Data Distiller Authorization API to manage IP-based access restrictions for Query Service by controlling which IP addresses are allowed.
  version: 1.0.0
servers:
- url: https://{environment}.adobe.io/
  variables:
    environment:
      default: platform
      enum:
      - platform
      - platform-stage
tags:
- name: IP Validation
  description: Use the IP Validation endpoint to verify if a specified IP address is permitted to access data within a designated sandbox in Query Service.
paths:
  /security/validate/ip-access:
    post:
      tags:
      - IP Validation
      summary: Validate IP access for a sandbox
      operationId: validateIPAddress
      parameters:
      - $ref: '#/components/parameters/authorization'
      - $ref: '#/components/parameters/content-type'
      - $ref: '#/components/parameters/x-gw-ims-org-id'
      - $ref: '#/components/parameters/x-api-key'
      - $ref: '#/components/parameters/x-sandbox-name'
      - $ref: '#/components/parameters/accept-encoding'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ipAddress:
                  type: string
                  description: The IP address to be validated for sandbox access.
                  example: 197.2.0.2
      responses:
        200:
          x-summary: Success
          description: A successful response returns a boolean indicating whether the IP is allowed to access the sandbox.
          content:
            application/json:
              schema:
                type: object
                properties:
                  isAllowed:
                    type: boolean
                    description: 'Indicates whether the specified IP address is permitted to access the sandbox. Returns `true` if access is allowed, and `false` otherwise.

                      '
                    example: true
        401:
          x-summary: Unauthorized
          description: The authentication credentials are missing or invalid.
        404:
          x-summary: Not Found
          description: The specified resource or endpoint was not found.
        500:
          x-summary: Internal Server Error
          description: An unexpected server error occurred.
components:
  parameters:
    x-api-key:
      name: x-api-key
      in: header
      description: The API key for Adobe Experience Platform.
      required: true
      schema:
        type: string
    authorization:
      name: Authorization
      in: header
      description: The bearer token for authorization.
      required: true
      schema:
        type: string
    content-type:
      name: Content-Type
      in: header
      description: The type of content being sent in the body of the request. The value should be 'application/json'.
      required: true
      schema:
        type: string
    accept-encoding:
      name: Accept-Encoding
      in: header
      description: The type of response encoding expected. The supported values are `gzip` and `identity`.
      required: false
      schema:
        type: string
        enum:
        - gzip
        - identity
        default: identity
    x-sandbox-name:
      name: x-sandbox-name
      in: header
      description: The name of the sandbox where the operation will take place.
      required: true
      schema:
        type: string
    x-gw-ims-org-id:
      name: x-gw-ims-org-id
      in: header
      description: The organization ID for Adobe Experience Platform.
      required: true
      schema:
        type: string
